language: node_js
node_js:
  - "6"

before_deploy:
  - npm run dist

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master

notifications:
  email:
    on_success: never
